management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    metrics:
      enabled=true:
spring:
  main:
    banner-mode: "off"
logging:
  logstash-tcp-endpoint: logstash:8089