version: "3"
services:
  application:
    image: sthyagarajan/adobe-romannumerals:1.0-SNAPSHOT
    ports:
      - 8080:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=local"
    depends_on:
      - prometheus
    networks:
      - front-tier
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ../metrics-monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ../metrics-monitoring/rules.yml:/etc/prometheus/rules.yml
    ports:
      - 9090:9090
    networks:
      - front-tier
  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - 9093:9093
    volumes:
      - ../metrics-monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - front-tier
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ../metrics-monitoring/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    networks:
      - front-tier
    depends_on:
      - prometheus
networks:
  front-tier:
    driver: bridge