version: "3"
services:
  application:
    image: sthyagarajan/adobe-romannumerals:1.0-SNAPSHOT
    ports:
      - 8080:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=local"
    networks:
      - front-tier
networks:
  front-tier:
    driver: bridge
